image: python:3.8-alpine

stages:
  - scrape

scrape:
  stage: scrape
  script:
    - ls -la ${watch}
    - pip install -r requirements.txt
    - python3 ./scrape.py -c cache.yaml -i ${watch}
  artifacts:
    paths:
      - cache.yaml
    expire_in: 1 day
    
    
