name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2,8,14,20 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARTIFACT_URL=$(gh api -q '.artifacts[0].archive_download_url' /repos/${{ github.repository }}/actions/artifacts)
          [ ! -z "${ARTIFACT_URL}" ] && curl -sLo artifact.zip -H "Authorization: token ${GH_TOKEN}" ${ARTIFACT_URL} && unzip artifact.zip && rm artifact.zip

      - name: Install prerequsites
        run: pip3 install -r requirements.txt

      - name: Checkout watch repository
        # Work-around secrets not accessible in conditionals as per https://github.com/actions/runner/issues/520
        env:
          SOURCEMON_WATCH_REPO: ${{ secrets.SOURCEMON_WATCH_REPO }}
        if: ${{ env.SOURCEMON_WATCH_REPO != null }}
        uses: actions/checkout@v3
        with: 
          repository: ${{ secrets.SOURCEMON_WATCH_REPO }}
          ssh-key: ${{ secrets.SOURCEMON_WATCH_REPO_KEY || '' }}
          token: ${{ secrets.SOURCEMON_WATCH_REPO_TOKEN || github.token }}
          path: watches

      - name: Execute watch
        run: python3 ./watch.py --cache ./cache.tar.gz ./watches/**/*.y*ml

      - uses: actions/upload-artifact@v3
        with:
          name: cache.tar.gz
          path: ./cache.tar.gz
          retention-days: 7